# Only for the GHC-compilable bits
flags: {}
packages:
  - libs/hs/blaze-react-core
  - libs/hs/blaze-react-dev-mode-server
  - libs/hs/blaze-react-dev-mode-shared
  - libs/hs/servant-blaze-react
extra-deps: []
resolver: lts-3.2

system-ghc: false
require-stack-version: ">= 0.1.5.0"
