# Only for the GHC-compilable bits
flags: {}
packages:
  - libs/hs/blaze-react-core
  - libs/hs/blaze-react-dev-mode-server
  - libs/hs/blaze-react-dev-mode-shared
  - libs/hs/blaze-react-examples
  - libs/hs/servant-blaze-react
  - apps/hs/blaze-react-todomvc

extra-deps: []

resolver: lts-5.13

system-ghc: false
install-ghc: true
require-stack-version: ">= 0.1.5.0"
